import type { Metadata } from "next";
import Navbar from "@/app/components/navbar/navbar";
import Footer from "@/app/components/footer/footer";

import { IBM_Plex_Sans, Space_Grotesk } from "next/font/google";

import "@/styles/primitives.css";
import "@/styles/semantics.css";
import "@/styles/globals.css";
import styles from "@/app/layout.module.scss";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-interface",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-headers",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "TidyCards",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <div className={styles['application-ui']}>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
