import type { Metadata } from 'next';
import { IBM_Plex_Sans, Space_Grotesk } from 'next/font/google';
import { cookies } from 'next/headers';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import { resendConfirmationEmail } from '@/actions/me';
import { getUser } from '@/lib/get-user';
import { getNewListGate } from '@/lib/new-list-gate';
import { normalizeThemePreference, resolveColorSchemeFromTheme, THEME_COOKIE_NAME } from '@/lib/theme-mapper';
import { UserProvider } from '@/providers/UserProvider';

import ConfirmEmailBanner from '@/components/Banner/ConfirmEmailBanner';
import Footer from '@/components/Footer/Footer';
import GlobalModals from '@/components/GlobalModals';
import { LanguageInitializer } from '@/components/LanguageInitializer';
import Navbar from '@/components/Navbar/Navbar';

import styles from '@/app/layout.module.scss';
import '@/styles/globals.css';
import '@/styles/primitives.css';
import '@/styles/semantics.css';

const ibmPlexSans = IBM_Plex_Sans({
  variable: '--font-interface',
  subsets: ['latin'],
  weight: ['400', '500'],
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-headers',
  subsets: ['latin'],
  weight: ['700'],
});

export const metadata: Metadata = {
  title: 'TidyCards',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read locale from our custom cookie (set by middleware/saveLanguagePreference)
  // This decouples us from next-intl's automatic locale detection
  const cookieStore = await cookies();
  const localeFromCookie = cookieStore.get('tidy_language')?.value ?? 'en';
  const locale = (localeFromCookie === 'en' || localeFromCookie === 'fr') ? localeFromCookie : 'en';
  const themePreference = normalizeThemePreference(cookieStore.get(THEME_COOKIE_NAME)?.value ?? null);
  const colorScheme = resolveColorSchemeFromTheme(themePreference);

  // Load messages for the detected locale
  const messages = await getMessages({ locale });
  const dateFormats = (messages.date as { formats?: Record<string, Intl.DateTimeFormatOptions> })?.formats ?? {};
  const newListGate = await getNewListGate();
  const user = await getUser();
  const shouldShowConfirmEmailBanner = user?.emailConfirmed === false;

  return (
    <html
      lang={locale}
      data-theme={themePreference}
      style={colorScheme ? { colorScheme } : undefined}
    >
      <head></head>
      <body className={`${ibmPlexSans.variable} ${spaceGrotesk.variable}`}>
        <NextIntlClientProvider locale={locale} messages={messages} formats={{ dateTime: dateFormats as Record<string, import('use-intl').DateTimeFormatOptions> }}>
          <UserProvider initialUser={user}>
            <div id="application-banners">
              {shouldShowConfirmEmailBanner && (
                <ConfirmEmailBanner onResend={resendConfirmationEmail} />
              )}
            </div>
            <div className={styles['application-ui']}>
              <Navbar />
              {children}
              <Footer />
            </div>
            <GlobalModals newListGate={newListGate} />
            <div id="application-overlays"></div>
          </UserProvider>
        </NextIntlClientProvider>
        {/* Ensure language cookie exists in browser */}
        <LanguageInitializer locale={locale} />
      </body>
    </html>
  );
}
