import type { Metadata } from 'next';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import GlobalModals from '@/components/GlobalModals';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import { IBM_Plex_Sans, Space_Grotesk } from 'next/font/google';

import '@/styles/primitives.css';
import '@/styles/semantics.css';
import '@/styles/globals.css';
import styles from '@/app/layout.module.scss';

const ibmPlexSans = IBM_Plex_Sans({
  variable: '--font-interface',
  subsets: ['latin'],
  weight: ['400', '500'],
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-headers',
  subsets: ['latin'],
  weight: ['700'],
});

export const metadata: Metadata = {
  title: 'TidyCards',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head></head>
      <body className={`${ibmPlexSans.variable} ${spaceGrotesk.variable}`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className={styles['application-ui']}>
            <Navbar />
            {children}
            <Footer />
          </div>
          <GlobalModals />
          <div id="application-overlays"></div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
