name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/storybook
          key: ${{ runner.os }}-storybook-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx', '**/*.mdx', '**/*.css', '**/*.scss') }}
          restore-keys: |
            ${{ runner.os }}-storybook-${{ hashFiles('**/package-lock.json') }}-

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - run: npm ci

      - name: Init MSW service worker
        run: npx msw init public --no-save

      - run: npm run build-storybook -- --output-dir storybook-static
        env:
          STORYBOOK_BASE_URL: /tidy-next

      - uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
